linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
      - (*github.com/spf13/cobra.Command).MarkFlagsMutuallyExclusive
      - (*github.com/briandowns/spinner.Spinner).Color
